import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "@/app/components/Navbar/Navbar";
import "./globals.scss";
import Footer from "@/app/components/Footer/Footer";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
});
const integralCF = localFont({
  src: [
    {
      path: "./fonts/integralCFRegular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/integralCFMediumRegular.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/integralCFBoldRegular.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-integral",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${satoshi.variable} ${integralCF.variable}`}>
      <body className="antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
